name: Deploy Private GitHub repository to cPanel
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: Get Code
    - name: Setup node version
      uses: actions/setup-node@v3
      with:
        node-version: 14
    - name: Install Node
      run: npm install
    - name: Build
      run: npm run build
    - name: Upload from output to a remote server via FTP
      uses: modern-dev/ftp-mirror@v2
      with:
        server: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local_dir: "./dist/"
        remote_dir: "/"
        delete: "true"
        exlude: "data/ cache/"
