# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package
on:
  push:
    branches:
      - master

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print environment variables
        run: |
          echo "Listing environment variables..."                
          env | sort | grep -v AWS
