# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package
on:
  push:
    branches:
      - master

jobs:
  view-env:
    runs-on: ubuntu-latest
    steps:
      - name: View Environment Variables
        uses: dawidd6/action-environment@v2
        with:
          prefix: GITHUB_
